# Generated by Django 3.1.2 on 2020-11-01 13:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Postid', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.TextField()),
                ('Category', models.TextField()),
                ('Description', models.TextField()),
                ('PostDate', models.DateField()),
                ('ImageId', models.TextField()),
            ],
            options={
                'db_table': 'Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Time', models.TimeField()),
                ('Location', models.TextField()),
                ('Delivery_status', models.TextField(default='Preparing')),
                ('MovingService', models.BooleanField(default=False)),
                ('OrderConfirm', models.BooleanField(default=False)),
                ('Postid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.post')),
                ('req_Userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
    ]
