# Generated by Django 3.1 on 2020-10-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postDate',
            new_name='PostDate',
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(),
        ),
    ]
