# Generated by Django 3.1 on 2020-10-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201022_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Userid',
            new_name='req_Userid',
        ),
    ]
